# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cats' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cats

  # UI
  pod 'SwiftPullToRefresh'
  pod 'SkeletonView'
  pod 'SwiftMessages’
  pod 'Kingfisher'
  pod 'FaveButton'

  # Architecture
  pod 'PromiseKit'
  
  # Network
  pod 'Alamofire'
  pod 'Moya'
  pod 'Result'
  pod 'SwiftyJSON'

end
